jobs:
- job: linux
  pool: {vmImage: 'Ubuntu-18.04'}
  strategy:
    matrix:
      gurobi:
        solver: 'gurobi'
      cplex:
        solver: 'cplex'
      ampls:
        solver: 'ampls'
  variables:
    wheelhouse: $(Build.ArtifactStagingDirectory)
  steps:
    - task: UsePythonVersion@0
    # - script: |
    #     sudo apt-get install swig
    #   displayName: Install SWIG
    - bash: |
        bash libs/download.sh
      displayName: Download libraries
    - bash: |
        set -ex
        mkdir -p tmp
        TMP=`pwd`/tmp
        cp support/twine.sh $WHEELHOUSE/twine.sh
        cd python/$SOLVER
        bash prepare.sh
        # bash swig.sh
        pip install --upgrade pip
        pip install urllib3[secure] --upgrade
        pip install cibuildwheel==1.6.2
        CIBW_SKIP='pp* *-manylinux*_i686' cibuildwheel --output-dir $TMP .
        ls -l $TMP
        test "$(ls -A $TMP)" || exit 1
        mv $TMP/* $WHEELHOUSE/
        python setup.py sdist -d $WHEELHOUSE
        # pip install twine
        # twine upload -u $(TWINE_USERNAME) -p $(TWINE_PASSWORD) $WHEELHOUSE/* || true
      displayName: Build wheels
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: '$(Build.ArtifactStagingDirectory)'}
- job: macos
  pool: {vmImage: 'macOS-10.15'}
  strategy:
    matrix:
      gurobi:
        solver: 'gurobi'
      cplex:
        solver: 'cplex'
      ampls:
        solver: 'ampls'
  variables:
    wheelhouse: $(Build.ArtifactStagingDirectory)
  steps: 
    - task: UsePythonVersion@0
    # - script: |
    #     brew install swig
    #   displayName: Install SWIG
    - bash: |
        bash libs/download.sh
      displayName: Download libraries
    - bash: |
        set -ex
        mkdir -p tmp
        TMP=`pwd`/tmp
        cd python/$SOLVER
        bash prepare.sh
        # bash swig.sh
        pip install --upgrade pip
        pip install urllib3[secure] --upgrade
        pip install cibuildwheel==1.6.2
        CIBW_SKIP='pp*' cibuildwheel --output-dir $TMP .
        ls -l $TMP
        test "$(ls -A $TMP)" || exit 1
        mv $TMP/* $WHEELHOUSE/
        # pip install twine
        # twine upload -u $(TWINE_USERNAME) -p $(TWINE_PASSWORD) $WHEELHOUSE/*.whl || true
      displayName: Build wheels
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: '$(Build.ArtifactStagingDirectory)'}
- job: windows
  pool: {vmImage: 'windows-2019'}
  strategy:
    matrix:
      gurobi:
        solver: 'gurobi'
      cplex:
        solver: 'cplex'
      ampls:
        solver: 'ampls'
  variables:
    wheelhouse: $(Build.ArtifactStagingDirectory)
  steps:
    - task: UsePythonVersion@0
    # - script: |
    #     choco install vcpython27 -f -y
    #   displayName: Install Visual C++ for Python 2.7
    # - script: |
    #     choco install -y --x86 swig
    #   displayName: Install SWIG
    - bash: |
        bash libs/download.sh
      displayName: Download libraries
    - bash: |
        set -ex
        mkdir -p tmp
        TMP=`pwd`/tmp
        cd python/$SOLVER
        bash prepare.sh
        # bash swig.sh
        python -m pip install --user --upgrade pip
        python -m pip install urllib3[secure] --upgrade
        python -m pip install cibuildwheel==1.6.4
        # Skipping python 2.7 (due to c++11) and 3.9 (linking error)
        CIBW_SKIP='*-win32 pp* cp27-* cp39-*' cibuildwheel --output-dir $TMP .
        ls -l $TMP
        test "$(ls -A $TMP)" || exit 1
        mv $TMP/* $WHEELHOUSE/
        # python -m pip install twine
        # python -m twine upload -u $(TWINE_USERNAME) -p $(TWINE_PASSWORD) $WHEELHOUSE/*.whl || true
      displayName: Build wheels
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: '$(Build.ArtifactStagingDirectory)'}
