jobs:
- job: linux
  pool: {vmImage: 'ubuntu-latest'}
  strategy:
    matrix:
      gurobi:
        solver: 'gurobi'
      cplex:
        solver: 'cplexmp'
        CIBW_MANYLINUX_X86_64_IMAGE: 'manylinux2014'
      xpress:
        solver: 'xpress'
  variables:
    wheelhouse: $(Build.ArtifactStagingDirectory)
  steps:
    - task: UsePythonVersion@0
    # - script: |
    #     sudo apt-get install swig
    #   displayName: Install SWIG
    - bash: |
        bash libs/download.sh
      displayName: Download libraries
    - bash: |
        set -ex
        mkdir -p tmp
        TMP=`pwd`/tmp
        cp support/twine.sh $WHEELHOUSE/twine.sh
        cd python/$SOLVER
        bash prepare.sh linux64
        bash swig.sh
        pip install --upgrade pip
        pip install urllib3[secure] --upgrade
        pip install cibuildwheel==1.12.0
        CIBW_SKIP='pp* *-manylinux*_i686 cp27-*' cibuildwheel --output-dir $TMP .
        ls -l $TMP
        test "$(ls -A $TMP)" || exit 1
        mv $TMP/* $WHEELHOUSE/
        bash prepare.sh # to package libs for all platforms
        python setup.py sdist -d $WHEELHOUSE
        # pip install twine
        # twine upload -u $(TWINE_USERNAME) -p $(TWINE_PASSWORD) $WHEELHOUSE/* || true
      displayName: Build wheels
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: '$(Build.ArtifactStagingDirectory)'}
- job: macos
  pool: {vmImage: 'macOS-latest'}
  strategy:
    matrix:
      gurobi:
        solver: 'gurobi'
      cplex:
        solver: 'cplexmp'
      xpress:
        solver: 'xpress'
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
  variables:
    wheelhouse: $(Build.ArtifactStagingDirectory)
  steps: 
    - task: UsePythonVersion@0
    # - script: |
    #     brew install swig
    #   displayName: Install SWIG
    - bash: |
        bash libs/download.sh
      displayName: Download libraries
    - bash: |
        set -ex
        mkdir -p tmp
        TMP=`pwd`/tmp
        cd python/$SOLVER
        bash prepare.sh osx64
        bash swig.sh
        pip install --upgrade pip
        pip install urllib3[secure] --upgrade
        pip install cibuildwheel==1.12.0
        CIBW_SKIP='pp*' cibuildwheel --output-dir $TMP .
        ls -l $TMP
        test "$(ls -A $TMP)" || exit 1
        mv $TMP/* $WHEELHOUSE/
        # pip install twine
        # twine upload -u $(TWINE_USERNAME) -p $(TWINE_PASSWORD) $WHEELHOUSE/*.whl || true
      displayName: Build wheels
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: '$(Build.ArtifactStagingDirectory)'}
- job: windows
  pool: {vmImage: 'windows-latest'}
  strategy:
    matrix:
      gurobi:
        solver: 'gurobi'
      cplex:
        solver: 'cplexmp'
      xpress:
        solver: 'xpress'
  variables:
    wheelhouse: $(Build.ArtifactStagingDirectory)
  steps:
    - task: UsePythonVersion@0
    # - script: |
    #     choco install vcpython27 -f -y
    #   displayName: Install Visual C++ for Python 2.7
    # - script: |
    #     choco install -y --x86 swig
    #   displayName: Install SWIG
    - bash: |
        bash libs/download.sh
      displayName: Download libraries
    - bash: |
        set -ex
        mkdir -p tmp
        TMP=`pwd`/tmp
        cd python/$SOLVER
        bash prepare.sh win64
        bash swig.sh
        python -m pip install --user --upgrade pip
        python -m pip install urllib3[secure] --upgrade
        python -m pip install cibuildwheel==1.12.0
        # Skipping python 2.7 (due to c++11)
        CIBW_SKIP='*-win32 pp* cp27-*' cibuildwheel --output-dir $TMP .
        ls -l $TMP
        test "$(ls -A $TMP)" || exit 1
        mv $TMP/* $WHEELHOUSE/
        # python -m pip install twine
        # python -m twine upload -u $(TWINE_USERNAME) -p $(TWINE_PASSWORD) $WHEELHOUSE/*.whl || true
      displayName: Build wheels
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: '$(Build.ArtifactStagingDirectory)'}
