/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_amplpy_gurobi_swig_WRAP_H_
#define SWIG_amplpy_gurobi_swig_WRAP_H_

#include <map>
#include <string>


class SwigDirector_GenericCallback : public GenericCallback, public Swig::Director {

public:
    SwigDirector_GenericCallback(PyObject *self);
    virtual int doAddCut(int nvars, int const *vars, double const *coeffs, char direction, double rhs, int type);
    virtual int doAddCutSwigPublic(int nvars, int const *vars, double const *coeffs, char direction, double rhs, int type) {
      return GenericCallback::doAddCut(nvars,vars,coeffs,direction,rhs,type);
    }
    virtual int run(int whereFrom);
    virtual ~SwigDirector_GenericCallback();
    virtual int getSolution(int len, double *sol);
    virtual double getObjective();
    virtual char const *getWhere(int wherefrom);
    virtual char const *getMessage();
    virtual AMPLCBWhere::Value getAMPLType();

/* Internal director utilities */
public:
    bool swig_get_inner(const char *swig_protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(swig_protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }
    void swig_set_inner(const char *swig_protected_method_name, bool swig_val) const {
      swig_inner[swig_protected_method_name] = swig_val;
    }
private:
    mutable std::map<std::string, bool> swig_inner;

#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
/* VTable implementation */
    PyObject *swig_get_method(size_t method_index, const char *method_name) const {
      PyObject *method = vtable[method_index];
      if (!method) {
        swig::SwigVar_PyObject name = SWIG_Python_str_FromChar(method_name);
        method = PyObject_GetAttr(swig_get_self(), name);
        if (!method) {
          std::string msg = "Method in class GenericCallback doesn't exist, undefined ";
          msg += method_name;
          Swig::DirectorMethodException::raise(msg.c_str());
        }
        vtable[method_index] = method;
      }
      return method;
    }
private:
    mutable swig::SwigVar_PyObject vtable[5];
#endif

};


class SwigDirector_GRBCallback : public GRBCallback, public Swig::Director {

public:
    SwigDirector_GRBCallback(PyObject *self);
    virtual int doAddCut(int nvars, int const *vars, double const *coeffs, char direction, double rhs, int type);
    virtual int doAddCutSwigPublic(int nvars, int const *vars, double const *coeffs, char direction, double rhs, int type) {
      return GRBCallback::doAddCut(nvars,vars,coeffs,direction,rhs,type);
    }
    virtual int run(int whereFrom);
    virtual ~SwigDirector_GRBCallback();
    virtual int getSolution(int len, double *sol);
    virtual double getObjective();
    virtual char const *getWhere(int where);
    virtual char const *getMessage();
    virtual AMPLCBWhere::Value getAMPLType();

/* Internal director utilities */
public:
    bool swig_get_inner(const char *swig_protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(swig_protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }
    void swig_set_inner(const char *swig_protected_method_name, bool swig_val) const {
      swig_inner[swig_protected_method_name] = swig_val;
    }
private:
    mutable std::map<std::string, bool> swig_inner;

#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
/* VTable implementation */
    PyObject *swig_get_method(size_t method_index, const char *method_name) const {
      PyObject *method = vtable[method_index];
      if (!method) {
        swig::SwigVar_PyObject name = SWIG_Python_str_FromChar(method_name);
        method = PyObject_GetAttr(swig_get_self(), name);
        if (!method) {
          std::string msg = "Method in class GRBCallback doesn't exist, undefined ";
          msg += method_name;
          Swig::DirectorMethodException::raise(msg.c_str());
        }
        vtable[method_index] = method;
      }
      return method;
    }
private:
    mutable swig::SwigVar_PyObject vtable[5];
#endif

};


#endif
